# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoneyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoneyApp
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftLint'
  pod 'SwiftDate'
  pod 'Toast-Swift'
  pod 'Moya'
  pod 'SGSwiftExtensions'
  pod 'SwiftLint'

  target 'MoneyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoneyAppUITests' do
    # Pods for testing
  end

end
